### PR TITLE
Updates to version 0.47.01

### PR DESCRIPTION
**Pull request by clcollins**
Updates the DwarfFortress version to 0.47.01.

Signed-off-by: Christopher Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by TC01** [comment]
Hi @clcollins,

Thanks for the PR; I'll merge it into RPM Fusion dist-git.

I'm the maintainer for dwarffortress in RPM Fusion; feel free to tag me for any future merge requests.

**Comment by clcollins** [comment]
:+1: Thanks @TC01 - for whatever reason I was failing to find you in the reviewers list, but that was probably my fault.  I'll tag you for anything in the future.

**Comment by clcollins** [comment]
Hi @TC01 - it looks like Toady just released 0.47.02.  I was going to ask if you wanted me to update the PR for that, but I see you've made changes to add 0.47.01 already.  Is there a different way you'd prefer?  I'm happy to keep an eye out for changes and help out submitting PRs and such, but I definitely want to do so in whatever workflow you prefer and not add any extra work for you.

**Comment by TC01** [comment]
Hi @clcollins,

Are you a Fedora packager? If so, and if you're interested, I could make you a co-maintainer of the RPM Fusion package-- it would be nice to have someone else actively looking after this! Anyone who's a Fedora packager can automatically become a RPM Fusion packager upon request.

Otherwise, I think pull requests are fine-- I just forgot to explicitly say I merged it manually.

I also still need to build 0.47 for Fedora 31. I think the policy I followed in the past was to update on Fedora N but to not update on Fedora N-1 (and then update dfhack/therapist in Fedora N whenever they are ready).

**Comment by clcollins** [comment]
Hi @TC01,

Unfortunately, I'm not a Fedora packager, though I have been wanting to get into it.  Maybe this will be the push I need to get involved more.  I will read up on that.  Until then, I'll just issue some PRs!

Thanks for the work you do on this.  I appreciate it, and I'm sure other Fedora Dwarf Fortress enthusiasts do as well.

**Comment by clcollins** [comment]
Hi @TC01, I'm going to close this, since you merged it a good while back.

I did submit a new PR for the latest version, 0.47.05, as well as an update to Dwarf Therapist.

**Pull request closed without merging**
