### PR TITLE
Updates to version 0.47.05

### PR DESCRIPTION
**Pull request by clcollins**
Updates the DwarfFortress version to 0.47.05.

Signed-off-by: Chris Collins <collins.christopher@gmail.com>

### CODE REVIEW

**Comment by clcollins** [comment]
@TC01, we chatted briefly on #2 about the possibility of adding me as an additional maintainer. I'm not a Fedora packager, but if you can direct me to whatever I need to do to get involved with the DF and DT packages, I'd be happy to help.

Thanks!

**Comment by TC01** [comment]
Hi @clcollins,

Thanks for the patches! I'll merge them in today (and also update dfhack).

It'd be great to have another person looking after the dwarffortress-related packages. If these were Fedora packages, I could [sponsor you as a co-maintainer](https://fedoraproject.org/wiki/How_to_get_sponsored_into_the_packager_group#Become_a_co-maintainer). I'm not entirely sure how this works for RPM Fusion if you're not first a Fedora packager; I'll find out and get back to you.

**Comment by clcollins** [comment]
Sounds great, thanks!

**Comment by TC01** [comment]
I checked in with @kwizart on IRC; if you go ahead and create a [RPM Fusion account](https://rpmfusion.org/Contributors#Get_an_RPM_Fusion_Account), someone will sponsor you, and then I can grant you access to the package.

That page should also detail how to use the [RPM Fusion  build infrastructure](https://rpmfusion.org/Contributors); it's very similar to the [corresponding Fedora infrastructure](https://fedoraproject.org/wiki/Join_the_package_collection_maintainers).

Thanks again for offering to help!

**Comment by TC01** [comment]
Hi @clcollins,

I granted you access to nonfree/dwarffortress, nonfree/dwarftherapist, and also nonfree/dfhack. ACLs get synchronized at 10 AM UTC every day, so by tomorrow morning you should be able to commit and build. I'll hold off on merging your commits for now so you can try pushing and building yourself; if you run into trouble feel free to let me know!

**Comment by clcollins** [comment]
Great!  Thank you, I'll do some reading tonight, and give things a shot this weekend.  Thanks for your help!

**Comment by clcollins** [comment]
Hi @TC01 - sorry to trouble you.  I've gotten all the accounts and things setup a while ago, but I cannot for the life of me get access to checkout the repo via rfpkg.  I get a permission denied message.

```
$ rfpkg clone rpmfusion/dwarffortress
Cloning into 'dwarffortress'...
FATAL: R any rpmfusion/dwarffortress clcollins DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Could not execute clone: Failed to execute command.
```

I believe I have the keys setup correctly, and I replaced the initial one I created with a new one just to be sure, but no luck.

Any guidance you can provide would be appreciated.

Also, if there's some other way you'd prefer to communicate about this, please let  me know. Whatever is easiest for you.

Thanks!

**Pull request closed without merging**
